/**
 * DOCLIX Markup Language renderer.
 *
 * Backward-compatible superset of the original Discord-style Markdown
 * renderer. Supports everything it did before (bold, italic, underline,
 * strikethrough, inline code, code blocks, # ## ### headings, lists,
 * blockquotes, links, images, tables, hr, ":::box", ":::columns") plus the
 * DOCLIX-native syntax:
 *
 *   <-Section-Title->            structural heading, level 1
 *   <-SubSection-Title->         structural heading, level 2
 *   <-SubSubSection-Title->      structural heading, level 3
 *   :::info / :::note / :::tip / :::warning / :::danger / :::success
 *                                 semantic callout containers (nestable)
 *   :::collapse "Label"           collapsible section
 *   :::tabs ... <-Tab-Name-> ... interactive tab group
 *   [[Page]] / [[Page|Text]]      internal DOCLIX document link
 *   [[Page#anchor]]               internal link with anchor
 *
 * Design: this is a two-pass, block-oriented parser, not a bag of regexes.
 * Pass 1 tokenizes the raw source into a flat list of block Tokens with a
 * simple bracket-matching scanner that understands nesting (containers can
 * contain containers, arrow elements, tabs, code fences, etc). Pass 2 walks
 * the token tree and renders each token to HTML. Code fences are located
 * and protected in the same tokenizing pass so nothing inside them is ever
 * misread as structural syntax.
 *
 * HTML safety: all raw text is escaped before any structural markers are
 * interpreted, and every value that ends up as an HTML attribute (href,
 * id, class, style) is generated by this module rather than passed through
 * verbatim, so user-authored text cannot break out of an attribute or
 * inject a tag/script.
 */

export interface HeadingItem {
  level: 1 | 2 | 3;
  text: string;
  id: string;
}

// Characters that can be backslash-escaped per standard Markdown (plus the
// DOCLIX-native "<" and ":" so "<-Section-...->" and ":::" fences can be
// escaped to appear literally, e.g. in documentation about DOCLIX itself).
const ESCAPABLE_CHARS = '\\`*_{}[]()#+-.!>~|<:';

// ---------------------------------------------------------------------------
// Shared small utilities
// ---------------------------------------------------------------------------

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Safe for use inside an HTML attribute value (already-escaped text). */
function attr(str: string): string {
  return escapeHtml(str);
}

function stripEscapes(text: string): string {
  let out = '';
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    const next = text[i + 1];
    if (ch === '\\' && next && ESCAPABLE_CHARS.includes(next)) {
      out += next;
      i++;
    } else {
      out += ch;
    }
  }
  return out;
}

/**
 * Replace backslash-escaped markdown-significant characters (e.g. "\*",
 * "\_", "\#", "\<", "\:") with a placeholder token holding the literal
 * character, so later block/inline parsing doesn't treat it as syntax.
 * Tokens are resolved back to plain text at the very end of rendering.
 */
function protectEscapedChars(text: string): string {
  let out = '';
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    const next = text[i + 1];
    if (ch === '\\' && next && ESCAPABLE_CHARS.includes(next)) {
      out += `\u0000ESC${next.charCodeAt(0)}\u0000`;
      i++;
    } else {
      out += ch;
    }
  }
  return out;
}

function restoreEscapedChars(html: string): string {
  return html.replace(/\u0000ESC(\d+)\u0000/g, (_m, code) => {
    const ch = String.fromCharCode(Number(code));
    return escapeHtml(ch);
  });
}

// A single seen-slug map is threaded through a whole render so that
// duplicate headings across the *entire* document (not just one nesting
// level) get collision-safe ids: "installation", "installation-2", ...
function slugify(text: string, seen: Map<string, number>): string {
  const base = text
    .toLowerCase()
    .trim()
    .replace(/&[a-z]+;/g, '')
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  const safeBase = base || 'section';
  const count = seen.get(safeBase) ?? 0;
  seen.set(safeBase, count + 1);
  return count === 0 ? safeBase : `${safeBase}-${count}`;
}

// ---------------------------------------------------------------------------
// extractHeadings — used by the ToC panel. Understands both "#"-style and
// DOCLIX-native "<-Section-...->" structural headings.
// ---------------------------------------------------------------------------

export function extractHeadings(source: string): HeadingItem[] {
  const lines = source.split('\n');
  const seen = new Map<string, number>();
  const headings: HeadingItem[] = [];
  let inFence = false; // ``` code fence
  let depth = 0; // ::: nesting depth — headings inside containers still count

  for (const line of lines) {
    const trimmed = line.trim();

    if (/^```/.test(trimmed)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;

    if (/^:::/.test(trimmed)) {
      if (trimmed === ':::') {
        depth = Math.max(0, depth - 1);
      } else {
        depth++;
      }
      continue;
    }

    const sectionMatch = trimmed.match(/^<-(Section|SubSection|SubSubSection)-(.*)->\s*$/);
    if (sectionMatch) {
      const level = sectionMatch[1] === 'Section' ? 1 : sectionMatch[1] === 'SubSection' ? 2 : 3;
      const text = stripEscapes(sectionMatch[2].trim());
      headings.push({ level: level as 1 | 2 | 3, text, id: slugify(sectionMatch[2], seen) });
      continue;
    }

    const h3 = line.match(/^###\s+(.*)/);
    const h2 = line.match(/^##\s+(.*)/);
    const h1 = line.match(/^#\s+(.*)/);
    if (h3) headings.push({ level: 3, text: stripEscapes(h3[1].trim()), id: slugify(h3[1], seen) });
    else if (h2) headings.push({ level: 2, text: stripEscapes(h2[1].trim()), id: slugify(h2[1], seen) });
    else if (h1) headings.push({ level: 1, text: stripEscapes(h1[1].trim()), id: slugify(h1[1], seen) });
  }

  return headings;
}

// ---------------------------------------------------------------------------
// Inline rendering (bold/italic/links/images/inline code/internal links)
// ---------------------------------------------------------------------------

export interface RenderOptions {
  /**
   * Slug of the current project, used to resolve internal DOCLIX links
   * ("[[Page]]") to a real href of the form "/docs/{projectSlug}/{page}".
   * If omitted, internal links render as "#" placeholders (still safe,
   * just non-navigable) so the renderer degrades gracefully wherever a
   * project context isn't available (e.g. isolated previews).
   */
  projectSlug?: string;
}

const DANGEROUS_URL = /^\s*(javascript|data|vbscript):/i;

function sanitizeUrl(url: string): string | null {
  const trimmed = url.trim();
  if (DANGEROUS_URL.test(trimmed)) return null;
  return trimmed;
}

function slugifyLinkTarget(text: string): string {
  return text
    .trim()
    .toLowerCase()
    .replace(/[^\w\s/-]/g, '')
    .replace(/\s+/g, '-');
}

function renderInline(text: string, opts: RenderOptions = {}): string {
  let out = text;

  // Inline code (protect content from further inline processing)
  const codeTokens: string[] = [];
  out = out.replace(/`([^`]+)`/g, (_m, code) => {
    codeTokens.push(code);
    return `\u0000CODE${codeTokens.length - 1}\u0000`;
  });

  // Internal DOCLIX links: [[Page]], [[Page|Text]], [[Page#anchor]],
  // [[Page#anchor|Text]]. Handled before external links/images since the
  // double-bracket syntax differs and must not be swallowed by them.
  out = out.replace(
    /\[\[([^\]|#]+)(?:#([^\]|]+))?(?:\|([^\]]+))?\]\]/g,
    (_m, page: string, anchor: string | undefined, label: string | undefined) => {
      const pageName = page.trim();
      const anchorName = (anchor ?? '').trim();
      const linkLabel = (label ?? pageName).trim();
      const targetSlug = slugifyLinkTarget(pageName);
      const base = opts.projectSlug
        ? `/docs/${encodeURIComponent(opts.projectSlug)}/${encodeURIComponent(targetSlug)}`
        : '#';
      const href = anchorName ? `${base}#${slugifyLinkTarget(anchorName)}` : base;
      return `<a href="${attr(href)}" class="doclix-internal-link" data-doclix-internal="1">${renderInline(
        linkLabel,
        opts
      )}</a>`;
    }
  );

  // Images ![alt](url) — must be handled before links, since the link
  // pattern would otherwise match the "[alt](url)" part and leave a stray "!".
  out = out.replace(/!\[([^\]]*)\]\((\S+?)\)/g, (_m, alt, url) => {
    const safe = sanitizeUrl(url);
    if (!safe) return '';
    return `<img src="${attr(safe)}" alt="${attr(alt)}" loading="lazy" />`;
  });

  // Links [text](url)
  out = out.replace(/\[([^\]]+)\]\((\S+?)\)/g, (_m, label, url) => {
    const safe = sanitizeUrl(url);
    if (!safe) return label;
    return `<a href="${attr(safe)}" target="_blank" rel="noopener noreferrer">${label}</a>`;
  });

  // Bold **text**
  out = out.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  // Underline __text__
  out = out.replace(/__([^_]+)__/g, '<u>$1</u>');
  // Strikethrough ~~text~~
  out = out.replace(/~~([^~]+)~~/g, '<del>$1</del>');
  // Italic *text* (single asterisks, after bold has been consumed)
  out = out.replace(/\*([^*]+)\*/g, '<em>$1</em>');

  // Restore code tokens
  out = out.replace(/\u0000CODE(\d+)\u0000/g, (_m, i) => {
    return `<code>${escapeHtml(codeTokens[Number(i)])}</code>`;
  });

  return out;
}

// ---------------------------------------------------------------------------
// Table helpers (unchanged behavior, kept for existing callers / tableOps)
// ---------------------------------------------------------------------------

export function isTableSeparatorRow(line: string): boolean {
  const trimmed = line.trim();
  if (!trimmed.includes('-') || !trimmed.includes('|')) return false;
  const cells = trimmed.replace(/^\|/, '').replace(/\|$/, '').split('|');
  return cells.length > 0 && cells.every((c) => /^\s*:?-+:?\s*$/.test(c));
}

export function splitTableRow(line: string): string[] {
  let trimmed = line.trim();
  if (trimmed.startsWith('|')) trimmed = trimmed.slice(1);
  if (trimmed.endsWith('|')) trimmed = trimmed.slice(0, -1);
  return trimmed.split('|').map((c) => c.trim());
}

// ---------------------------------------------------------------------------
// Box colors (kept from the original ":::box" feature)
// ---------------------------------------------------------------------------

export const BOX_COLORS = ['violet', 'blue', 'green', 'amber', 'red', 'gray'] as const;
export type BoxColor = (typeof BOX_COLORS)[number];

const BOX_COLOR_HEX: Record<BoxColor, string> = {
  violet: '#8b5cf6',
  blue: '#3b82f6',
  green: '#22c55e',
  amber: '#f59e0b',
  red: '#ef4444',
  gray: '#6b7280',
};

function isBoxColor(value: string): value is BoxColor {
  return (BOX_COLORS as readonly string[]).includes(value);
}

// ---------------------------------------------------------------------------
// Callout container kinds
// ---------------------------------------------------------------------------

export const CALLOUT_KINDS = ['info', 'note', 'tip', 'warning', 'danger', 'success'] as const;
export type CalloutKind = (typeof CALLOUT_KINDS)[number];

function isCalloutKind(value: string): value is CalloutKind {
  return (CALLOUT_KINDS as readonly string[]).includes(value);
}

const CALLOUT_LABEL: Record<CalloutKind, string> = {
  info: 'Info',
  note: 'Note',
  tip: 'Tip',
  warning: 'Warning',
  danger: 'Danger',
  success: 'Success',
};

// ---------------------------------------------------------------------------
// Tokenizer
//
// Turns raw source into a flat array of top-level Block tokens. Container
// blocks (callouts, collapse, tabs, box, columns) hold their inner raw text
// unparsed — it's recursively run back through render() at render time,
// which is what allows arrow syntax / nested containers to work inside a
// container without the outer scanner needing to understand every possible
// nested construct up front.
// ---------------------------------------------------------------------------

type Block =
  | { type: 'codeblock'; lang: string; code: string }
  | { type: 'heading'; level: 1 | 2 | 3; hashStyle: boolean; text: string }
  | { type: 'hr' }
  | { type: 'table'; header: string[]; align: string[]; rows: string[][] }
  | { type: 'blockquote'; lines: string[] }
  | { type: 'list'; kind: 'ul' | 'ol'; items: string[] }
  | { type: 'box'; color: BoxColor; title: string; body: string }
  | { type: 'columns'; left: string; right: string }
  | { type: 'callout'; kind: CalloutKind; body: string }
  | { type: 'collapse'; label: string; body: string }
  | { type: 'tabs'; tabs: { title: string; body: string }[] }
  | { type: 'paragraph'; text: string };

const SECTION_OPEN = /^<-(Section|SubSection|SubSubSection)-(.*)->\s*$/;
const TAB_OPEN = /^<-Tab-(.*)->\s*$/;

/**
 * Find the matching ":::" close for a container that was opened at `start`
 * (the line AFTER the opening fence). Nested ":::..." opens increase depth;
 * bare ":::" closes decrease it. Code fences inside the container are
 * skipped over so a "```" block containing literal ":::" text can never
 * accidentally close (or nest) a container.
 */
function findContainerClose(lines: string[], start: number): number {
  let depth = 1;
  let i = start;
  let inCodeFence = false;
  while (i < lines.length) {
    const trimmed = lines[i].trim();
    if (/^```/.test(trimmed)) {
      inCodeFence = !inCodeFence;
      i++;
      continue;
    }
    if (!inCodeFence) {
      if (trimmed === ':::') {
        depth--;
        if (depth === 0) return i;
      } else if (/^:::\S/.test(trimmed)) {
        depth++;
      }
    }
    i++;
  }
  return lines.length; // unterminated — fail gracefully, treat rest as body
}

function tokenize(source: string): Block[] {
  const lines = source.split('\n');
  const blocks: Block[] = [];
  let i = 0;
  let listBuffer: { kind: 'ul' | 'ol'; items: string[] } | null = null;

  function flushList() {
    if (listBuffer) {
      blocks.push({ type: 'list', kind: listBuffer.kind, items: listBuffer.items });
      listBuffer = null;
    }
  }

  while (i < lines.length) {
    const line = lines[i];
    const trimmed = line.trim();

    // Fenced code block — protected verbatim, never scanned for structure.
    if (/^```/.test(trimmed)) {
      flushList();
      const lang = trimmed.slice(3).trim();
      const codeLines: string[] = [];
      i++;
      while (i < lines.length && !/^```/.test(lines[i].trim())) {
        codeLines.push(lines[i]);
        i++;
      }
      i++; // skip closing fence
      blocks.push({ type: 'codeblock', lang, code: codeLines.join('\n') });
      continue;
    }

    // ":::" containers — box, columns, collapse, tabs, and semantic callouts.
    const boxOpen = trimmed.match(/^:::box(?:\s+(\S+))?(?:\s+"([^"]*)")?\s*$/);
    const columnsOpen = /^:::columns\s*$/.test(trimmed);
    const collapseOpen = trimmed.match(/^:::collapse(?:\s+"([^"]*)")?\s*$/);
    const tabsOpen = /^:::tabs\s*$/.test(trimmed);
    const calloutOpen = trimmed.match(/^:::([a-zA-Z]+)\s*$/);

    if (boxOpen) {
      flushList();
      const colorArg = (boxOpen[1] || '').toLowerCase();
      const color: BoxColor = isBoxColor(colorArg) ? colorArg : 'violet';
      const title = boxOpen[2] || '';
      const closeAt = findContainerClose(lines, i + 1);
      const body = lines.slice(i + 1, closeAt).join('\n');
      blocks.push({ type: 'box', color, title, body });
      i = closeAt + 1;
      continue;
    }

    if (columnsOpen) {
      flushList();
      const closeAt = findContainerClose(lines, i + 1);
      const bodyLines = lines.slice(i + 1, closeAt);
      const sepIdx = bodyLines.findIndex((l) => l.trim() === '---');
      const left = sepIdx === -1 ? bodyLines.join('\n') : bodyLines.slice(0, sepIdx).join('\n');
      const right = sepIdx === -1 ? '' : bodyLines.slice(sepIdx + 1).join('\n');
      blocks.push({ type: 'columns', left, right });
      i = closeAt + 1;
      continue;
    }

    if (collapseOpen) {
      flushList();
      const label = collapseOpen[1] || 'Click to expand';
      const closeAt = findContainerClose(lines, i + 1);
      const body = lines.slice(i + 1, closeAt).join('\n');
      blocks.push({ type: 'collapse', label, body });
      i = closeAt + 1;
      continue;
    }

    if (tabsOpen) {
      flushList();
      const closeAt = findContainerClose(lines, i + 1);
      const bodyLines = lines.slice(i + 1, closeAt);
      const tabs: { title: string; body: string }[] = [];
      let j = 0;
      // Skip any stray content before the first <-Tab-...-> marker (ignored,
      // fails gracefully rather than crashing on malformed input).
      while (j < bodyLines.length && !TAB_OPEN.test(bodyLines[j].trim())) j++;
      while (j < bodyLines.length) {
        const m = bodyLines[j].trim().match(TAB_OPEN);
        if (!m) {
          j++;
          continue;
        }
        const title = m[1].trim();
        j++;
        const contentLines: string[] = [];
        while (j < bodyLines.length && !TAB_OPEN.test(bodyLines[j].trim())) {
          contentLines.push(bodyLines[j]);
          j++;
        }
        tabs.push({ title, body: contentLines.join('\n') });
      }
      blocks.push({ type: 'tabs', tabs });
      i = closeAt + 1;
      continue;
    }

    if (calloutOpen && isCalloutKind(calloutOpen[1].toLowerCase())) {
      flushList();
      const kind = calloutOpen[1].toLowerCase() as CalloutKind;
      const closeAt = findContainerClose(lines, i + 1);
      const body = lines.slice(i + 1, closeAt).join('\n');
      blocks.push({ type: 'callout', kind, body });
      i = closeAt + 1;
      continue;
    }

    // DOCLIX structural heading: <-Section-Title-> / <-SubSection-Title-> / <-SubSubSection-Title->
    const sectionMatch = trimmed.match(SECTION_OPEN);
    if (sectionMatch) {
      flushList();
      const level = sectionMatch[1] === 'Section' ? 1 : sectionMatch[1] === 'SubSection' ? 2 : 3;
      blocks.push({ type: 'heading', level: level as 1 | 2 | 3, hashStyle: false, text: sectionMatch[2] });
      i++;
      continue;
    }

    // Tables: header row, separator row (---|---), then body rows.
    if (trimmed.includes('|') && i + 1 < lines.length && isTableSeparatorRow(lines[i + 1])) {
      flushList();
      const header = splitTableRow(line);
      const align = splitTableRow(lines[i + 1]).map((c) => {
        const left = c.startsWith(':');
        const right = c.endsWith(':');
        if (left && right) return 'center';
        if (right) return 'right';
        if (left) return 'left';
        return '';
      });
      i += 2;
      const rows: string[][] = [];
      while (i < lines.length && lines[i].trim().includes('|') && lines[i].trim() !== '') {
        rows.push(splitTableRow(lines[i]));
        i++;
      }
      blocks.push({ type: 'table', header, align, rows });
      continue;
    }

    // Horizontal rule
    if (/^-{3,}$/.test(trimmed)) {
      flushList();
      blocks.push({ type: 'hr' });
      i++;
      continue;
    }

    // "#"-style headings (kept for backward compatibility)
    const h3 = line.match(/^###\s+(.*)/);
    const h2 = line.match(/^##\s+(.*)/);
    const h1 = line.match(/^#\s+(.*)/);
    if (h3) {
      flushList();
      blocks.push({ type: 'heading', level: 3, hashStyle: true, text: h3[1] });
      i++;
      continue;
    }
    if (h2) {
      flushList();
      blocks.push({ type: 'heading', level: 2, hashStyle: true, text: h2[1] });
      i++;
      continue;
    }
    if (h1) {
      flushList();
      blocks.push({ type: 'heading', level: 1, hashStyle: true, text: h1[1] });
      i++;
      continue;
    }

    // Blockquote
    if (/^>\s?/.test(line)) {
      flushList();
      const quoteLines = [line.replace(/^>\s?/, '')];
      i++;
      while (i < lines.length && /^>\s?/.test(lines[i])) {
        quoteLines.push(lines[i].replace(/^>\s?/, ''));
        i++;
      }
      blocks.push({ type: 'blockquote', lines: quoteLines });
      continue;
    }

    // Numbered list
    const ol = line.match(/^\d+\.\s+(.*)/);
    if (ol) {
      if (!listBuffer || listBuffer.kind !== 'ol') {
        flushList();
        listBuffer = { kind: 'ol', items: [] };
      }
      listBuffer.items.push(ol[1]);
      i++;
      continue;
    }

    // Bullet list
    const ul = line.match(/^[-*]\s+(.*)/);
    if (ul) {
      if (!listBuffer || listBuffer.kind !== 'ul') {
        flushList();
        listBuffer = { kind: 'ul', items: [] };
      }
      listBuffer.items.push(ul[1]);
      i++;
      continue;
    }

    // Blank line
    if (trimmed === '') {
      flushList();
      i++;
      continue;
    }

    // Paragraph
    flushList();
    blocks.push({ type: 'paragraph', text: line });
    i++;
  }

  flushList();
  return blocks;
}

// ---------------------------------------------------------------------------
// Renderer — walks tokens to HTML, sharing a single heading-slug map across
// the whole render (threaded through recursive calls) so anchors stay
// unique across nested containers/tabs too.
// ---------------------------------------------------------------------------

let tabGroupCounter = 0;

// A single "cell" of inline content (paragraph line, table cell, list item,
// heading label, collapse/tab label) goes through the escape-then-inline
// pipeline.
function renderCell(raw: string, opts: RenderOptions): string {
  const escaped = escapeHtml(protectEscapedChars(raw));
  return restoreEscapedChars(renderInline(escaped, opts));
}

function renderBlocks(blocks: Block[], opts: RenderOptions, slugSeen: Map<string, number>): string {
  const html: string[] = [];

  function slugFor(text: string): string {
    return slugify(text, slugSeen);
  }

  for (const block of blocks) {
    switch (block.type) {
      case 'codeblock': {
        const code = escapeHtml(block.code);
        html.push(
          `<div class="doclix-codeblock"><button type="button" class="doclix-copy-btn" data-doclix-copy aria-label="Copy code"><span class="doclix-copy-label">Copy</span></button><pre><code${
            block.lang ? ` class="language-${attr(block.lang)}"` : ''
          }>${code}</code></pre></div>`
        );
        break;
      }
      case 'heading': {
        const id = slugFor(block.text);
        const tag = `h${block.level}`;
        const cls = block.hashStyle ? '' : ` class="doclix-heading doclix-heading-${block.level}"`;
        html.push(`<${tag} id="${attr(id)}"${cls}>${renderCell(block.text.trim(), opts)}</${tag}>`);
        break;
      }
      case 'hr':
        html.push('<hr />');
        break;
      case 'table': {
        const alignStyle = (idx: number) => (block.align[idx] ? ` style="text-align:${block.align[idx]}"` : '');
        const thead = `<thead><tr>${block.header
          .map((c, idx) => `<th${alignStyle(idx)}>${renderCell(c, opts)}</th>`)
          .join('')}</tr></thead>`;
        const tbody = `<tbody>${block.rows
          .map(
            (row) => `<tr>${row.map((c, idx) => `<td${alignStyle(idx)}>${renderCell(c, opts)}</td>`).join('')}</tr>`
          )
          .join('')}</tbody>`;
        html.push(`<div class="doclix-table-wrap"><table>${thead}${tbody}</table></div>`);
        break;
      }
      case 'blockquote':
        html.push(`<blockquote>${block.lines.map((l) => renderCell(l, opts)).join('<br/>')}</blockquote>`);
        break;
      case 'list':
        html.push(
          `<${block.kind}>${block.items.map((item) => `<li>${renderCell(item, opts)}</li>`).join('')}</${block.kind}>`
        );
        break;
      case 'box': {
        const hex = BOX_COLOR_HEX[block.color];
        const titleHtml = block.title ? `<div class="doclix-box-title">${renderCell(block.title, opts)}</div>` : '';
        html.push(
          `<div class="doclix-box doclix-box-${block.color}" style="--doclix-box-color:${hex}">${titleHtml}${render(
            block.body,
            opts,
            slugSeen
          )}</div>`
        );
        break;
      }
      case 'columns':
        html.push(
          `<div class="doclix-columns"><div class="doclix-column">${render(
            block.left,
            opts,
            slugSeen
          )}</div><div class="doclix-column">${render(block.right, opts, slugSeen)}</div></div>`
        );
        break;
      case 'callout': {
        const label = CALLOUT_LABEL[block.kind];
        html.push(
          `<div class="doclix-callout doclix-callout-${block.kind}" role="note"><div class="doclix-callout-label">${label}</div><div class="doclix-callout-body">${render(
            block.body,
            opts,
            slugSeen
          )}</div></div>`
        );
        break;
      }
      case 'collapse': {
        const label = renderCell(block.label, opts);
        html.push(
          `<details class="doclix-collapse"><summary class="doclix-collapse-summary">${label}</summary><div class="doclix-collapse-body">${render(
            block.body,
            opts,
            slugSeen
          )}</div></details>`
        );
        break;
      }
      case 'tabs': {
        if (block.tabs.length === 0) break;
        const groupId = `doclix-tabgroup-${++tabGroupCounter}`;
        const tabButtons = block.tabs
          .map(
            (t, idx) =>
              `<button type="button" class="doclix-tab-btn${
                idx === 0 ? ' doclix-tab-btn-active' : ''
              }" data-doclix-tab-btn data-tab-index="${idx}">${renderCell(t.title, opts)}</button>`
          )
          .join('');
        const panels = block.tabs
          .map(
            (t, idx) =>
              `<div class="doclix-tab-panel${
                idx === 0 ? ' doclix-tab-panel-active' : ''
              }" data-doclix-tab-panel data-tab-index="${idx}">${render(t.body, opts, slugSeen)}</div>`
          )
          .join('');
        html.push(
          `<div class="doclix-tabs" id="${groupId}" data-doclix-tabs><div class="doclix-tab-list" role="tablist">${tabButtons}</div><div class="doclix-tab-panels">${panels}</div></div>`
        );
        break;
      }
      case 'paragraph':
        html.push(`<p>${renderCell(block.text, opts)}</p>`);
        break;
    }
  }

  return html.join('\n');
}

/**
 * Render a chunk of DOCLIX source (top-level document, or the body of a
 * container/tab/collapse) to HTML, sharing the heading-slug map so ids stay
 * unique across the whole document even when headings appear inside
 * containers.
 */
function render(source: string, opts: RenderOptions, slugSeen: Map<string, number>): string {
  const blocks = tokenize(source);
  return renderBlocks(blocks, opts, slugSeen);
}

export function renderMarkdown(source: string, projectSlugOrOpts?: string | RenderOptions): string {
  const opts: RenderOptions =
    typeof projectSlugOrOpts === 'string' ? { projectSlug: projectSlugOrOpts } : projectSlugOrOpts || {};
  const slugSeen = new Map<string, number>();
  return render(source, opts, slugSeen);
}
